{% set name = "datasketches" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c00d61da4695e00036e63f590999f584cc39246cbb147b171f375f792604a612
    patches:
      - patches/0001-add-ninja-generator.patch  # [win]
      - patches/0002-use-local-datasketches-cpp.patch
      - patches/0003-fix-osx-linker.patch  # [osx]
      - patches/0004-prevent-adding-debug-symbol-in-the-_datasketches-nam.patch  # [win]
    folder: datasketches
  - url: https://github.com/apache/{{ name }}-cpp/archive/refs/tags/{{ version }}.tar.gz
    sha256: 63e6bda660ee9730cc39746de87fd983118c28149e32ff9389fac98b27010a53
    folder: datasketches-cpp

build:
  number: 0
  script: |
    cd datasketches
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]
  missing_dso_whitelist:  # [s390x]
    - "$RPATH/ld64.so.1"  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.16
    - make  # [not win]
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - nanobind >=1.6
    - setuptools >=30.3.0
    - wheel
  run:
    - python
    - numpy

# Assertion errors: calculations problem appears only on s390x.
{% set ignore_tests = "" %}
{% set ignore_tests = ignore_tests + " --ignore=datasketches/tests/theta_test.py" %}  # [s390x]
{% set ignore_tests = ignore_tests + " --ignore=datasketches/tests/tuple_test.py" %}  # [s390x]

test:
  source_files:
    - datasketches/tests
  imports:
    - datasketches
  commands:
    - pip check
    # Windows fatal exception: code 0x80000003
    # Program: test_envilib\site-packages\_datasketches.cp39-win_amd64.pyd
    # File: C: Program Files (x86) \Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\Include\optional
    # Line: 359
    # Expression: Cannot access value of empty optional
    - pytest -v {{ ignore_tests }} {{ name }}/tests  # [not win]
  requires:
    - pip
    - pytest

about:
  home: https://datasketches.apache.org
  summary: The Apache DataSketches Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file:
    - {{ name }}/LICENSE
    - {{ name }}-cpp/LICENSE
  dev_url: https://github.com/apache/datasketches-python
  doc_url: https://datasketches.apache.org/
  description: |
    A software library of stochastic streaming algorithms.
    In the analysis of big data there are often problem queries that don't scale because they require huge compute resources and time to generate exact results. Examples include count distinct, quantiles, most-frequent items, joins, matrix computations, and graph analysis.
    If approximate results are acceptable, there is a class of specialized algorithms, called streaming algorithms, or sketches that can produce results orders-of magnitude faster and with mathematically proven error bounds. For interactive queries there may not be other viable alternatives, and in the case of real-time analysis, sketches are the only known solution.
    This package provides a variety of sketches as described below. Wherever a specific type of sketch exists in Apache DataSketches packages for other languages, the sketches will be portable between languages (for platforms with the same endianness).

extra:
  recipe-maintainers:
    - rxm7706
